name: Run Campaign Pipeline

on:
  schedule:
    # 11:30 AM IST → 06:00 UTC (Morning)
    - cron: '0 6 * * *'

    # 5:00 PM IST → 11:30 UTC (Evening)
    - cron: '30 11 * * *'

  workflow_dispatch:
    inputs:
      slot:
        description: 'Choose slot to run'
        required: true
        default: 'morning'

jobs:
  run-morning:
    if: github.event_name == 'schedule' && github.event.schedule == '0 6 * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.slot == 'morning')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Create token.json
        run: echo '${{ secrets.GOOGLE_TOKEN }}' > token.json

      - name: Run morning campaign
        run: python run_campaign.py --slot morning --live


  run-evening:
    if: github.event_name == 'schedule' && github.event.schedule == '30 11 * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.slot == 'evening')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Create token.json
        run: echo '${{ secrets.GOOGLE_TOKEN }}' > token.json

      - name: Run evening campaign
        run: python run_campaign.py --slot evening