name: Run Campaign Pipeline (Live)

on:
  schedule:
    # 11:00 AM IST → 05:30 UTC (Morning)
    - cron: '30 5 * * *'

    # 5:00 PM IST → 11:30 UTC (Evening)
    - cron: '30 11 * * *'

  workflow_dispatch:

jobs:
  run-morning:
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Create token.json
        run: echo '${{ secrets.GOOGLE_TOKEN }}' > token.json

      - name: Set date variable (IST)
        run: echo "TODAY=$(TZ='Asia/Kolkata' date +'%d%m%Y')" >> $GITHUB_ENV

      - name: Run morning campaign (LIVE)
        run: python run_campaign.py --slot morning --date $TODAY


  run-evening:
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Create token.json
        run: echo '${{ secrets.GOOGLE_TOKEN }}' > token.json

      - name: Set date variable (IST)
        run: echo "TODAY=$(TZ='Asia/Kolkata' date +'%d%m%Y')" >> $GITHUB_ENV

      - name: Run evening campaign (LIVE)
        run: python run_campaign.py --slot evening --date $TODAY